version: '3'

volumes:
  mysql_data:

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    tty: true
    stdin_open: true

  mysql:
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rails:
    build:
      context: ./rails
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./rails:/myapp
    ports:
      - 3000:3000
    depends_on:
      - mysql
    tty: true
    stdin_open: true