version: '3'
services:
  rails:
    build:
      context: ./rails
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./rails:/myapp
    ports:
      - 3000:3000
    tty: true
    stdin_open: true